- hosts: all
  become: yes

  tasks:

    - name: Atualizar sistema
      apt:
        update_cache: yes
        upgrade: dist

    - name: Instalar pacotes base
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Adicionar chave GPG da Docker
      shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg

    - name: Adicionar repositório da Docker
      shell: |
        echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
        $(. /etc/os-release && echo $VERSION_CODENAME) stable" | \
        tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Atualizar cache após adicionar repo
      apt:
        update_cache: yes

    - name: Instalar Docker oficial + Compose v2
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Iniciar e habilitar docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Copiar docker-compose.yml
      copy:
        src: docker-compose.yml
        dest: /home/vagrant/docker-compose.yml

    - name: Subir containers
      command: docker compose up -d
      args:
        chdir: /home/vagrant

